/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const USER_ROLE = {
	ADMIN: "ADMIN",
	USER: "USER",
} as const;

export type USER_ROLE = (typeof USER_ROLE)[keyof typeof USER_ROLE];

export const STATUS = {
	ACTIVE: "ACTIVE",
	COMPLETED: "COMPLETED",
	CANCELLED: "CANCELLED",
} as const;

export type STATUS = (typeof STATUS)[keyof typeof STATUS];

export const PRIORITY = {
	LOW: "LOW",
	MEDIUM: "MEDIUM",
	HIGH: "HIGH",
} as const;

export type PRIORITY = (typeof PRIORITY)[keyof typeof PRIORITY];
